config/routes.rb
Rails.application.routes.draw do
  resources :climbers, only: [:index, :new, :show, :create, :edit, :update, :destroy]
  resources :climbs, only: [:index, :new, :show, :create]
  resources :ticks, only: [:new, :create]
  get 'sessions/destroy'

  root 'climbs#index'

  # post 'sessions/reset' to: 'sessions#reset'
  # make a post request to sessions/reset to the reset method in the sessions controller

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :subscriptions
  has_many :climbers, through: :subscriptions






end

app/models/climb.rb
class Climb < ApplicationRecord
  has_many :comments
  has_many :climbers, through: :comments
  has_many :ticks
  has_many :climbers, through: :ticks








end

app/models/climber.rb
class Climber < ApplicationRecord
  has_many :comments
  has_many :climbs, through: :comments
  has_many :ticks, dependent: :destroy
  has_many :climbs, through: :ticks
  has_many :subscriptions
  has_many :articles, through: :subscriptions

  validates :username, uniqueness: true
  has_secure_password



  # def password=(plaintext_password)
  #   self.password_digest = BCrypt::Password.create(plaintext_password)
  # end
  #
  # def authenticate(plaintext_password)
  #   BCrypt::Password.new(self.password_digest) == plaintext_password
  # end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :climber
  belongs_to :climb
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :climber
  belongs_to :article
end

app/models/tick.rb
class Tick < ApplicationRecord
  belongs_to :climber
  belongs_to :climb
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_climber
  before_action :authorized



  private

  def authorized
    if @current_climber == nil
      redirect_to login_path
    end
  end


  def set_current_climber
    @current_climber = Climber.find_by(id: session[:climber_id])
  end

end

app/controllers/climbers_controller.rb
class ClimbersController < ApplicationController
  before_action :set_climber, only: [:show, :edit, :update, :destroy]
  before_action :authorize_climber, only: [:edit, :update, :destroy]
  skip_before_action :authorized, only: [:new, :create]



  def index
    @climbers = Climber.all
  end

  def new
    @climber = Climber.new
  end

  def create
    climber = Climber.create(climber_params)
    if climber.valid?
      session[:climber_id] = climber.id
      redirect_to climber
    else
      flash[:errors] = climber.errors.full_messages
      redirect_to new_climber_path
    end
  end

  def show
    # if session["page_views"] == nil
    #   session["page_views"] = 5
    # end
    # session["page_views"] = session["page_views"] - 1
    # @page_views = session["page_views"]
    # @climber = Climber.find(params[:id])
  end


  def edit
    # @climber = Climber.find(params[:id])
    render :edit
  end


  def update
    # @climber = Climber.find(params[:id])
    @climber.update(climber_params)

    redirect_to @climber
  end


  def destroy
    # @climber = Climber.find(params[:id])
    @climber.destroy

    redirect_to climbs_path
  end

  private

  def authorize_climber
    if @climber != @current_climber
      redirect_to climbs_path
    end
  end


  def climber_params
    params.require(:climber).permit(:name, :username, :password)
  end


  def set_climber
    @climber = Climber.find(params[:id])
  end
end

app/controllers/climbs_controller.rb
class ClimbsController < ApplicationController
  require 'json'
  before_action :set_climb, only: [:show]

  def index
    @climbs = Climb.all
  end

  def new
    @climb = Climb.new
  end

  def create
    climb = Climb.create(climb_params)
    if climb.valid?
      redirect_to climb
    else
      flash[:errors] = climb.errors.full_messages
      redirect_to new_climb_path
    end
  end

  def show
    # set_climb see above
    @tick = Tick.new
    @weather = RestClient::Request.execute(
      method: :get,
      url: "https://api.openweathermap.org/data/2.5/weather?q=#{@climb.location}",
      headers: {params: {APPID: ENV['APPID']}})
    @weather = JSON.parse(@weather)

    
  end

  private

  def set_climb
    @climb = Climb.find(params[:id])
  end


  def climb_params
    params.require(:climb).permit(:name, :length, :difficulty, :location)
  end

end

app/controllers/ticks_controller.rb
class TicksController < ApplicationController
  def index
    @ticks = Tick.all
  end

  def new
    @tick = Tick.new
  end

  def create
    merged_params = tick_params.merge(climber_id: @current_climber.id)
    @tick = Tick.create(merged_params)
    # climb = Climb.find(tick_params[:climb_id])
    if @tick.valid?
      redirect_to climb_path(@tick.climb)
    else
      flash[:errors] = @tick.errors.full_messages
      redirect_to climbers_path
    end
  end

  def show
    @tick = Tick.find(params[:id])
  end

  private

  def tick_params
    params.require(:tick).permit(:climber_id, :climb_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/climbers_helper.rb
module ClimbersHelper
end

app/helpers/climbs_helper.rb
module ClimbsHelper
end

app/helpers/ticks_helper.rb
module TicksHelper
end

app/views/climbers/index.html.erb
<%= button_to "Create Climber", new_climber_path, method: :get, class: "button" %>
<%= button_to "View Climbs", climbs_path, method: :get, class: "button" %>


<h1>All the Climbers</h1>
<ul>
  <% @climbers.each do |climber| %>
    <li>
      <%= link_to climber.name, climber %>
    </li>
  <% end %>
</ul>

app/views/climbers/new.html.erb
<h2>Signup as a New Climber</h2>
<%= form_for @climber do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :name, "Username" %>
  <%= f.text_field :username %>
  <%= f.label :name, "Password" %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

app/views/climbers/show.html.erb
<%= button_to "View Climbers", climbers_path, method: :get, class: "button" %>
<%= button_to "View Climbs", climbs_path, method: :get, class: "button" %>
<%= button_to "Create Tick", new_tick_path, method: :get, class: "button" %>

<% if @current_climber.id == @climber.id %>
  <%= button_to "Edit Climber", edit_climber_path, method: :get, class: "button" %>
  <%= link_to "Delete", @climber, method: :delete %>
<% end %>



<h1><%= @climber.name %></h1>

<h1>All My Climbs</h1>
<ul>
  <% @climber.climbs.each do |climb| %>
    <li>
      <%= link_to climb.name, climb %>
    </li>
  <% end %>
</ul>

app/views/climbs/index.html.erb
<h1>All the Climbs</h1>
<ul>
  <% @climbs.each do |climb| %>
    <li>
      <%= link_to climb.name, climb %>
    </li>
  <% end %>
</ul>

app/views/climbs/new.html.erb
<h2>New Climb</h2>
<%= form_for @climb do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :location, "Location" %>
  <%= f.text_field :location %>
  <%= f.label :length, "Length" %>
  <%= f.number_field :length %>
  <%= f.label :difficulty, "Difficulty" %>
  <%= f.number_field :difficulty %>
  <%= f.submit %>
<% end %>

app/views/climbs/show.html.erb
<h1> Name:  <%= @climb.name %></h1>

<h1> Location:  <%= @climb.location %></h1>

<h1> Length:  <%= @climb.length %> feet </h1>

<h1> Difficulty:  <%= @climb.difficulty %></h1>

<h1> Temperature:  <%= (@weather['main']['temp'] - 273.15).round(2) %> Celsius </h1>

<h1> Humidity:  <%= (@weather['main']['humidity']) %>% </h1>



<h1>All Ticks</h1>
<ul>
  <% @climb.climbers.each do |climber| %>
    <li>
      <%= link_to climber.name, climber %>
    </li>
  <% end %>
</ul>


<h3>Create a New Tick</h3>
<%= form_for @tick do |f| %>
  <%= f.label :climber_id, "Climber" %><br>
  <%= f.hidden_field :climber_id, value: @current_climber.id %><br>
  <%= f.hidden_field :climb_id, value: @climb.id %>
  <%= f.submit %>
<% end %>
<%= button_to "Back to Climbs", climbs_path, method: :get, class: "button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Send</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/ticks/new.html.erb
<%= form_for @tick do |f|%>


    <%#                      should match label, collection, what you want, what they see %>
    <%= f.label :climb_id, "Climb" %> <br>
    <%= f.collection_select :climb_id, Climb.all, :id, :name, prompt: true %><br>
    <%= f.hidden_field :climber_id, value: @current_climber.id %><br>


    <%= f.submit %>
<% end %>